# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "C:/Users/user/AppData/Local/Temp/Rtmpg1DSBe/pins-74e0714d53b4")
v <- vetiver_pin_read(b, "`stroke prediction`", version = "20240227T011256Z-9d9bd")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}